export {UserModel} from "./user/user-model";
export {CarVariantModel} from "./manufacturer/car-variant-model";
export {CarBrandModel} from "./manufacturer/car-brand-model";
export {AdBannerModel} from "./ad-banner/ad-banner-model";
export {PostModel} from "./post/post-model";
export {CarModel} from "./car/car-model";
export {OtpModel} from "./otp/otp-model";
export * from "./common/interface"
export * from "./manufacturer/interface"
export * from "./otp/interface"
export * from "./user/interface"
export * from "./post/interface"
export * from "./car/interface"
export * from "./manufacturer/interface"
export * from "./ad-banner/interface"